doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '8.0.41'
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid: 'Symfony\Bridge\Doctrine\Types\UuidType'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        controller_resolver:
            auto_mapping: false
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src'
                prefix: 'App'
                alias: App
