when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
        orm:
            reset:
                mode: migrate
        make_factory:
            default_namespace: Tests\Factories

when@test: *dev
