when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
        orm:
            reset:
                mode: migrate
                migrations:
                    configurations:
                    - '%kernel.project_dir%/config/migrations/test-migrations.php'

        make_factory:
            default_namespace: Tests\Factories

when@test: *dev
