services:
  opensearch:
    environment:
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    deploy:
      resources:
        limits:
          memory: 1500M

  opensearch-dashboards:
    deploy:
      resources:
        limits:
          memory: 500M
